# Generated by Django 3.2.5 on 2021-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('dt_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('email', models.EmailField(max_length=60)),
                ('telefone', models.CharField(max_length=40)),
                ('cpf_rg', models.CharField(max_length=40, verbose_name='CPF ou RG')),
                ('participa_almoco', models.BooleanField(default=False, verbose_name='Participará do Almoço de Confraternização')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
